/** Bilingual strings for the header account link, the client project page and the admin console. */
import type { Lang } from "@/lib/i18n";

const dict = {
  fr: {
    access: { signedOut: "Accès client", signedIn: "Espace client" },
    project: {
      back: "Tous les projets",
      reference: "Référence",
      location: "Emplacement",
      service: "Service",
      status: "Statut",
      description: "Description",
      deliverables: "Livrables",
      none: "Aucun livrable publié pour ce projet.",
      published: "Publié le",
      download: "Télécharger",
      preparing: "Préparation…",
      notFound: "Ce projet est introuvable ou n’est pas associé à votre compte.",
    },
    admin: {
      console: "Console DRONE AIR",
      nav: {
        home: "Aperçu",
        clients: "Clients",
        projects: "Projets",
        missions: "Demandes",
        files: "Documents",
      },
      denied: "Accès refusé. Ce module est réservé à l’administration DRONE AIR.",
      counts: {
        missions: "Demandes de mission",
        newMissions: "nouvelles",
        clients: "Clients",
        projects: "Projets actifs",
        files: "Documents",
        published: "publiés",
      },
      actions: { newClient: "Nouveau client", newProject: "Nouveau projet", upload: "Téléverser" },
      search: "Rechercher",
      all: "Tous",
      loading: "Chargement…",
      empty: "Aucun enregistrement.",
      save: "Enregistrer",
      cancel: "Annuler",
      create: "Créer",
      edit: "Modifier",
      open: "Ouvrir",
      remove: "Retirer",
      history: "Historique",
      client: "Client",
      project: "Projet",
      contact: "Contact",
      projects: "Projets",
      files: "Fichiers",
      status: "Statut",
      updated: "Mis à jour",
      reference: "Référence",
      location: "Emplacement",
      service: "Service",
      name: "Nom",
      email: "Courriel",
      language: "Langue",
      description: "Description",
      version: "Version",
      category: "Catégorie",
      displayName: "Nom affiché",
      originalName: "Fichier d’origine",
      size: "Taille",
      type: "Type",
      created: "Créé",
      publishedAt: "Publié",
      visibility: "Visibilité",
      privateLabel: "Privé",
      publishedLabel: "Publié",
      archivedLabel: "Archivé",
      unverified: "Non vérifié",
      publish: "Publier",
      unpublish: "Retirer",
      archive: "Archiver",
      restore: "Restaurer",
      replace: "Remplacer",
      savePrivate: "Enregistrer privé",
      members: "Comptes autorisés",
      linkAccount: "Associer un compte existant",
      lookup: "Vérifier le courriel",
      confirmLink: "Confirmer l’association",
      noAccount: "Aucun compte n’existe pour ce courriel. Le client doit d’abord créer son accès.",
      accountFound: "Compte trouvé",
      uploadTitle: "Téléverser un livrable",
      dropHere: "Déposez le fichier ici",
      or: "ou",
      chooseFile: "Choisir un fichier",
      selectClientFirst: "Sélectionnez d’abord un client.",
      uploadStates: {
        uploading: "Téléversement",
        processing: "Traitement",
        verified: "Vérifié",
        failed: "Échec",
      },
      allowed: "Types acceptés",
      maxSize: "Taille maximale",
      missionDetail: "Demande de mission",
      internalOnly: "Information interne — jamais visible par le client.",
      aiSummary: "Résumé automatisé",
      aiQuestions: "Questions de suivi",
      emailLog: "Journal des courriels",
      attachment: "Pièce jointe",
      desiredDate: "Date souhaitée",
      area: "Superficie",
      createClientFromRequest: "Créer un client à partir de la demande",
      createProjectFromRequest: "Créer un projet à partir de la demande",
      requestStatus: "Statut interne",
    },
  },
  en: {
    access: { signedOut: "Client access", signedIn: "Client area" },
    project: {
      back: "All projects",
      reference: "Reference",
      location: "Location",
      service: "Service",
      status: "Status",
      description: "Description",
      deliverables: "Deliverables",
      none: "No deliverables have been published for this project.",
      published: "Published",
      download: "Download",
      preparing: "Preparing…",
      notFound: "This project cannot be found or is not linked to your account.",
    },
    admin: {
      console: "DRONE AIR console",
      nav: {
        home: "Overview",
        clients: "Clients",
        projects: "Projects",
        missions: "Requests",
        files: "Files",
      },
      denied: "Access denied. This module is restricted to DRONE AIR administration.",
      counts: {
        missions: "Mission requests",
        newMissions: "new",
        clients: "Clients",
        projects: "Active projects",
        files: "Files",
        published: "published",
      },
      actions: { newClient: "New client", newProject: "New project", upload: "Upload" },
      search: "Search",
      all: "All",
      loading: "Loading…",
      empty: "No records.",
      save: "Save",
      cancel: "Cancel",
      create: "Create",
      edit: "Edit",
      open: "Open",
      remove: "Remove",
      history: "History",
      client: "Client",
      project: "Project",
      contact: "Contact",
      projects: "Projects",
      files: "Files",
      status: "Status",
      updated: "Updated",
      reference: "Reference",
      location: "Location",
      service: "Service",
      name: "Name",
      email: "Email",
      language: "Language",
      description: "Description",
      version: "Version",
      category: "Category",
      displayName: "Display name",
      originalName: "Original filename",
      size: "Size",
      type: "Type",
      created: "Created",
      publishedAt: "Published",
      visibility: "Visibility",
      privateLabel: "Private",
      publishedLabel: "Published",
      archivedLabel: "Archived",
      unverified: "Unverified",
      publish: "Publish",
      unpublish: "Unpublish",
      archive: "Archive",
      restore: "Restore",
      replace: "Replace",
      savePrivate: "Save private",
      members: "Authorized accounts",
      linkAccount: "Link an existing account",
      lookup: "Check email",
      confirmLink: "Confirm link",
      noAccount: "No account exists for that email. The client must create their access first.",
      accountFound: "Account found",
      uploadTitle: "Upload deliverable",
      dropHere: "Drop file here",
      or: "or",
      chooseFile: "Choose file",
      selectClientFirst: "Select a client first.",
      uploadStates: {
        uploading: "Uploading",
        processing: "Processing",
        verified: "Verified",
        failed: "Failed",
      },
      allowed: "Accepted types",
      maxSize: "Maximum size",
      missionDetail: "Mission request",
      internalOnly: "Internal information — never visible to the client.",
      aiSummary: "Automated summary",
      aiQuestions: "Follow-up questions",
      emailLog: "Email log",
      attachment: "Attachment",
      desiredDate: "Desired date",
      area: "Area",
      createClientFromRequest: "Create client from request",
      createProjectFromRequest: "Create project from request",
      requestStatus: "Internal status",
    },
  },
} as const;

export type PortalCopy = (typeof dict)["fr"];

export function portalCopy(lang: Lang): PortalCopy {
  return dict[lang] as PortalCopy;
}
